language: python
python:
    - '2.7'
install: pip install -r requirements.txt --use-mirrors
script: make test
before_script:
    - psql -c 'create database memorandi;' -U postgres
env:
    global:
        - DJANGO_SETTINGS_MODULE=memorandi.settings.development
        - SECRET_KEY=supersecretkey
        - DB_NAME=memorandi
        - DB_USER=postgres
        - DB_PASS=''
        - DB_HOST=localhost
        - DB_PORT=5432
        - EMAIL_HOST_PASSWORD=''
notifications:
    email:
        recipients:
            - benjamin@bengfort.com
        on_success: change
        on_failure: always
